#!/bin/sh

echo "Use o seguinte comando para saber pacotes especiais desse servidor"
echo "  ajuda"

printf "\n"
printf " * Issues no GitHub:  https://github.com/fititnt/cplp-aiops/issues?q=is%3Aissue+is%3Aopen+label%3Aserver-aguia-pescadora\n"
#printf " * Management:     https://landscape.canonical.com\n"
#printf " * Support:        https://ubuntu.com/advantage\n"
